const screens=[...document.querySelectorAll('.screen')];let step=1;let picked=false;let found=0;
function show(n){step=n;screens.forEach((s,i)=>s.classList.toggle('active',i===n-1));window.scrollTo({top:0,behavior:'smooth'})}
function next(){if(step===2&&!picked){document.getElementById('choiceMsg').textContent='Escolhe uma primeiro, viajante 🌙';return}if(step<5)show(step+1)}
function prev(){if(step>1)show(step-1)}
function choose(el,c){document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');picked=true;const m={azul:'Então hoje eu fico pertinho, sem exigir que você sorria. 💙',cinza:'Tudo bem não saber explicar. Eu não preciso de explicação para ficar.',vermelho:'Respira. Você não precisa carregar o mundo inteiro de uma vez.',roxo:'Guarda essa esperança. Às vezes ela começa pequenininha mesmo. 💜'};document.getElementById('choiceMsg').textContent=m[c]}
function makeStars(){const box=document.getElementById('constellation');box.innerHTML='';const pts=[[15,58],[30,35],[45,52],[60,24],[75,45]];const memories=['Você já chegou mais longe do que imagina.','Nem todo dia precisa ser um dia perfeito.','Seu esforço também conta quando ninguém vê.','Você merece descansar sem se sentir culpado.','E, se esquecer de tudo isso, eu lembro por você. 💙'];pts.forEach((p,i)=>{const s=document.createElement('button');s.className='cstar';s.style.left=p[0]+'%';s.style.top=p[1]+'%';s.setAttribute('aria-label','estrela '+(i+1));s.onclick=()=>{if(!s.dataset.found){s.dataset.found='1';s.style.boxShadow='0 0 25px 10px rgba(255,229,163,.65)';found++;document.getElementById('xp').textContent=found*20;document.getElementById('starMsg').textContent='✦ '+memories[i];if(found===pts.length){document.getElementById('starMsg').textContent='🌟 CONSTELAÇÃO COMPLETA — “eu acredito em você.”';document.getElementById('continue3').disabled=false}}};box.appendChild(s)});for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],line=document.createElement('div');line.className='line';const dx=b[0]-a[0],dy=b[1]-a[1];line.style.left=a[0]+'%';line.style.top=a[1]+'%';line.style.width=Math.hypot(dx,dy)+'%';line.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';box.appendChild(line)}}
function restart(){picked=false;found=0;makeStars();document.getElementById('continue3').disabled=true;show(1)}
function heartRain(){const msg=document.getElementById('finalMsg');msg.textContent='Promete uma coisa: hoje você vai se tratar com um pouquinho mais de carinho. O resto a gente resolve aos poucos. ❤️';for(let i=0;i<24;i++){const h=document.createElement('div');h.textContent=['❤','✦','♡'][Math.floor(Math.random()*3)];h.style.position='fixed';h.style.left=Math.random()*100+'vw';h.style.top='-20px';h.style.zIndex=9;h.style.fontSize=(16+Math.random()*22)+'px';h.style.color=Math.random()>.5?'#ff8dbb':'#ffe5a3';h.style.transition='transform 2.8s linear,opacity 2.8s';document.body.appendChild(h);requestAnimationFrame(()=>{h.style.transform='translateY(110vh) rotate('+(Math.random()*360)+'deg)';h.style.opacity='0'});setTimeout(()=>h.remove(),3000)}}
function stars(){const sky=document.getElementById('sky');for(let i=0;i<95;i++){const s=document.createElement('i');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*4)+'s';s.style.opacity=.2+Math.random()*.7;sky.appendChild(s)}}
stars();makeStars();